export const pushStatusKeyList = [{ text: '待维修', value: '0' }, { text: '正常', value: '1' }, {text: '维修中', value: '2'}]
export const auditTypeList = [{ text: '已审核', value: 1 }, { text: '未审核', value: 0 }]
export const noticeTypeKeyList = [{ text: '安全防范公告', value: 'SAFE_GUARD_INFORM' }, { text: '物业风采', value: 'OFFICE_STYLE' }, { text: '电梯维修保养', value: 'ELEVATOR_MAINTENANCE' }, { text: '投票及调查互动', value: 'INVESTIGATE_INTERACT' }, { text: '商店优惠公告', value: 'STORE_PREFERENTIAL' }]
export const pushChannelKeyList = [{ text: 'APP推送', value: 'APP' }, { text: '短信', value: 'SMS' }]
export const strategyKeyList = [{ text: '立即生效', value: 'IMMEDIATE' }, { text: '定时生效', value: 'TIMES' }]
